import type { Saree, Order } from './types';

/**
 * Sample saree data for frontend development.
 * In production, this comes from the backend API.
 */
export const sampleSarees: Saree[] = [
  {
    id: 'saree-001',
    name: 'Royal Magenta Ikat Silk',
    description:
      'A stunning pure silk saree featuring traditional Pochampally ikat patterns in rich magenta and gold. The intricate geometric motifs are created using the resist-dyeing technique passed down through generations. This saree comes with a matching blouse piece and is perfect for weddings, festivals, and special celebrations.',
    priceInPaisa: 850000,
    mrpInPaisa: 1200000,
    fabric: 'SILK',
    weave: 'IKAT',
    color: 'Magenta',
    lengthInMeters: 6.3,
    blousePieceIncluded: true,
    images: [
      '/sarees/saree-silk-blue.jpg',
      '/sarees/saree-red-gold.jpg',
      '/sarees/saree-ikat-pattern.jpg',
    ],
    videoUrl: '/sarees/weaving-loom.mp4',
    stock: 5,
    active: true,
    createdAt: '2026-03-15T10:00:00Z',
  },
  {
    id: 'saree-002',
    name: 'Indigo Telia Rumal Cotton',
    description:
      'An exquisite handwoven Telia Rumal saree in deep indigo blue with traditional oil-treated cotton. This centuries-old technique from Pochampally produces a distinctive sheen and nool. The geometric ikat patterns are woven with natural dyes, making each piece unique.',
    priceInPaisa: 450000,
    mrpInPaisa: 600000,
    fabric: 'COTTON',
    weave: 'TELIA_RUMAL',
    color: 'Indigo',
    lengthInMeters: 6.0,
    blousePieceIncluded: true,
    images: [
      '/sarees/saree-maroon-silk.jpg',
      '/sarees/saree-weaving.jpg',
    ],
    videoUrl: '/sarees/fabric-texture.mp4',
    stock: 8,
    active: true,
    createdAt: '2026-03-10T10:00:00Z',
  },
  {
    id: 'saree-003',
    name: 'Emerald Green Silk Cotton',
    description:
      'A beautiful silk-cotton blend saree in emerald green with contrasting maroon border. The ikat weave creates mesmerizing diamond patterns that catch the light beautifully. Lightweight yet elegant, perfect for both daily wear and festive occasions.',
    priceInPaisa: 350000,
    mrpInPaisa: 500000,
    fabric: 'SILK_COTTON',
    weave: 'IKAT',
    color: 'Green',
    lengthInMeters: 6.3,
    blousePieceIncluded: true,
    images: [
      '/sarees/saree-red-gold.jpg',
      '/sarees/saree-maroon-silk.jpg',
    ],
    stock: 12,
    active: true,
    createdAt: '2026-03-20T10:00:00Z',
  },
  {
    id: 'saree-004',
    name: 'Coral Mercerized Cotton',
    description:
      'A vibrant coral mercerized cotton saree with golden zari border. The mercerization process gives the cotton a silk-like lustre while maintaining breathability. Traditional Pochampally geometric patterns adorn this light and elegant piece.',
    priceInPaisa: 280000,
    mrpInPaisa: 380000,
    fabric: 'COTTON',
    weave: 'MERCERIZED',
    color: 'Coral',
    lengthInMeters: 6.0,
    blousePieceIncluded: true,
    images: [
      '/sarees/saree-red-gold.jpg',
      '/sarees/saree-maroon-silk.jpg',
    ],
    stock: 15,
    active: true,
    createdAt: '2026-03-25T10:00:00Z',
  },
  {
    id: 'saree-005',
    name: 'Midnight Blue Double Ikat',
    description:
      'A rare double ikat silk saree in midnight blue where both the warp and weft threads are resist-dyed before weaving. This incredibly complex technique produces perfectly aligned patterns visible on both sides. A collector\'s masterpiece.',
    priceInPaisa: 1500000,
    mrpInPaisa: 2000000,
    fabric: 'SILK',
    weave: 'IKAT',
    color: 'Blue',
    lengthInMeters: 6.3,
    blousePieceIncluded: true,
    images: [
      '/sarees/saree-red-gold.jpg',
      '/sarees/saree-maroon-silk.jpg',
    ],
    stock: 2,
    active: true,
    createdAt: '2026-03-28T10:00:00Z',
  },
  {
    id: 'saree-006',
    name: 'Turmeric Yellow Silk',
    description:
      'A vibrant turmeric yellow pure silk saree with traditional ikat patterns in contrasting black and red. Symbolizing prosperity and auspiciousness, this saree is ideal for festive occasions. Features a rich pallu with intricate geometric designs.',
    priceInPaisa: 780000,
    mrpInPaisa: 950000,
    fabric: 'SILK',
    weave: 'IKAT',
    color: 'Yellow',
    lengthInMeters: 6.3,
    blousePieceIncluded: true,
    images: [
      '/sarees/saree-red-gold.jpg',
      '/sarees/saree-maroon-silk.jpg',
    ],
    stock: 6,
    active: true,
    createdAt: '2026-04-01T10:00:00Z',
  },
  {
    id: 'saree-007',
    name: 'Maroon Telia Rumal Silk',
    description:
      'A majestic maroon Telia Rumal silk saree with the distinctive oil-treated finish that gives it an unmatched nool and lustre. The traditional geometric patterns are created using natural dyes and the ancient resist-dyeing technique.',
    priceInPaisa: 920000,
    mrpInPaisa: 1100000,
    fabric: 'SILK',
    weave: 'TELIA_RUMAL',
    color: 'Maroon',
    lengthInMeters: 6.3,
    blousePieceIncluded: true,
    images: [
      '/sarees/saree-red-gold.jpg',
      '/sarees/saree-maroon-silk.jpg',
    ],
    stock: 4,
    active: true,
    createdAt: '2026-04-02T10:00:00Z',
  },
  {
    id: 'saree-008',
    name: 'Ivory Mercerized Bridal',
    description:
      'An elegant ivory mercerized cotton saree with elaborate gold and red border work. The mercerized finish provides a sophisticated sheen, while the delicate ikat patterns add timeless beauty. A versatile piece suitable for both casual and semi-formal occasions.',
    priceInPaisa: 320000,
    mrpInPaisa: 450000,
    fabric: 'COTTON',
    weave: 'MERCERIZED',
    color: 'Ivory',
    lengthInMeters: 6.0,
    blousePieceIncluded: true,
    images: [
      '/sarees/saree-red-gold.jpg',
      '/sarees/saree-maroon-silk.jpg',
    ],
    stock: 10,
    active: true,
    createdAt: '2026-04-03T10:00:00Z',
  },
];

export const sampleOrders: Order[] = [
  {
    id: 'order-001',
    orderNumber: 'PCH-20260401-001',
    items: [
      {
        sareeId: 'saree-001',
        sareeName: 'Royal Magenta Ikat Silk',
        priceInPaisa: 850000,
        quantity: 1,
      },
    ],
    address: {
      name: 'Lakshmi Devi',
      phone: '+919876543210',
      email: 'lakshmi@example.com',
      addressLine1: '42, Temple Street',
      city: 'Hyderabad',
      state: 'Telangana',
      pincode: '500001',
    },
    status: 'DELIVERED',
    razorpayPaymentId: 'pay_NxR7gQ2VBk9kPz',
    totalInPaisa: 850000,
    gstInPaisa: 42500,
    shippingInPaisa: 0,
    grandTotalInPaisa: 892500,
    trackingNumber: 'DTDC1234567890',
    createdAt: '2026-04-01T14:30:00Z',
    updatedAt: '2026-04-03T09:00:00Z',
  },
  {
    id: 'order-002',
    orderNumber: 'PCH-20260402-002',
    items: [
      {
        sareeId: 'saree-003',
        sareeName: 'Emerald Green Silk Cotton',
        priceInPaisa: 350000,
        quantity: 2,
      },
      {
        sareeId: 'saree-004',
        sareeName: 'Coral Mercerized Cotton',
        priceInPaisa: 280000,
        quantity: 1,
      },
    ],
    address: {
      name: 'Priya Sharma',
      phone: '+919123456789',
      email: 'priya@example.com',
      addressLine1: '18, MG Road',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560001',
    },
    status: 'SHIPPED',
    razorpayPaymentId: 'pay_QkT4mN8vRw2xYz',
    totalInPaisa: 980000,
    gstInPaisa: 49000,
    shippingInPaisa: 0,
    grandTotalInPaisa: 1029000,
    trackingNumber: 'BWKN9876543210',
    createdAt: '2026-04-02T11:00:00Z',
    updatedAt: '2026-04-03T16:00:00Z',
  },
  {
    id: 'order-003',
    orderNumber: 'PCH-20260404-003',
    items: [
      {
        sareeId: 'saree-005',
        sareeName: 'Midnight Blue Double Ikat',
        priceInPaisa: 1500000,
        quantity: 1,
      },
    ],
    address: {
      name: 'Ananya Reddy',
      phone: '+919876512345',
      email: 'ananya@example.com',
      addressLine1: '7, Jubilee Hills',
      city: 'Hyderabad',
      state: 'Telangana',
      pincode: '500033',
    },
    status: 'PAID',
    razorpayPaymentId: 'pay_Lm5nPq7sWx3yAb',
    totalInPaisa: 1500000,
    gstInPaisa: 75000,
    shippingInPaisa: 0,
    grandTotalInPaisa: 1575000,
    createdAt: '2026-04-04T09:15:00Z',
    updatedAt: '2026-04-04T09:20:00Z',
  },
];
